package com.example.flighttracking.model;

import jakarta.persistence.*;

/**
 * Represents a city in the database with a name and a unique airport code.
 * This class is a JPA entity, mapped to the 'cities' table.
 */
@Entity
@Table(name = "cities")
public class City {

    // Unique ID for the city, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The name of the city.
    private String name;

    // The airport code for the city (e.g., "AMD", "YYZ").
    @Column(name = "airport_code", unique = true)
    private String airportCode;

    // Default constructor is required by JPA.
    public City() {
    }

    // The constructor that was missing.
    public City(String name, String airportCode) {
        this.name = name;
        this.airportCode = airportCode;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAirportCode() {
        return airportCode;
    }

    public void setAirportCode(String airportCode) {
        this.airportCode = airportCode;
    }
}
